import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Load local fonts with variable support
const geistSans = localFont({
  src: "/fonts/GeistVF.woff",  // Correct path for fonts in the 'public' directory
  variable: "--font-geist-sans",
  weight: "100 900",  // Valid weight range
});
const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff", // Correct path
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
